version: '3.8'

services:
  app:
#    image: php:8.2-fpm
    build:
      context: .
      dockerfile: Dockerfile

    container_name: symfony_app
    working_dir: /var/www/symfony
   
    volumes:
      - ../guestbook:/var/www/symfony
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - symfony
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SYMFONY_ENV=dev
    depends_on:
      - database

  web:
    image: nginx:alpine
    container_name: symfony_web
    working_dir: /var/www/symfony
    volumes:
      - ../guestbook:/var/www/symfony          # Montez votre projet Symfony local dans le conteneur
      - ./nginx.conf:/etc/nginx/nginx.conf   # Utilisez une configuration Nginx personnalisée
    ports:
      - "8080:80"   # Mapping du port 80 (conteneur) au port 8080 (hôte)
    networks:
      - symfony
    depends_on:
      - app

  database:
    image: postgres:15
    container_name: symfony_db
    environment:
      # POSTGRES_DB: ${POSTGRES_DB:-app}
      # POSTGRES_USER: ${POSTGRES_USER:-symfony}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_DB: app
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: ChangeMe
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony
  
  adminer:
    image: adminer
    container_name: symfony_adminer
    depends_on:
      - database
    ports:
      - "8090:8080"
    networks:
      - symfony

networks:
  symfony:
     driver: bridge
volumes:
  db_data:
