# Utilisez l'image PHP-FPM officielle comme base
FROM php:8.2-fpm

# Installez les dépendances nécessaires
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

# Configurez le répertoire de travail
WORKDIR /var/www/symfony

# Copiez les fichiers de votre application dans le conteneur
COPY . /var/www/symfony